/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as HomeAccountRouteRouteImport } from './routes/home/account/route'
import { Route as HomeSidebarRouteRouteImport } from './routes/home/_sidebar/route'
import { Route as HomeAccountIndexRouteImport } from './routes/home/account/index'
import { Route as AuthTwoFactorIndexRouteImport } from './routes/auth/two-factor/index'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/auth/forgot-password/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as HomeSidebarARouteImport } from './routes/home/_sidebar/a'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as HomeAccountTwoFactorIndexRouteImport } from './routes/home/account/two-factor/index'
import { Route as HomeAccountSecurityIndexRouteImport } from './routes/home/account/security/index'
import { Route as HomeAccountEmailIndexRouteImport } from './routes/home/account/email/index'
import { Route as HomeAccountDangerZoneIndexRouteImport } from './routes/home/account/danger-zone/index'
import { Route as AuthTwoFactorOtpIndexRouteImport } from './routes/auth/two-factor/otp/index'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/admin/users/$userId/index'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const HomeAccountRouteRoute = HomeAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSidebarRouteRoute = HomeSidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAccountIndexRoute = HomeAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeAccountRouteRoute,
} as any)
const AuthTwoFactorIndexRoute = AuthTwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const HomeSidebarARoute = HomeSidebarARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => HomeSidebarRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAccountTwoFactorIndexRoute =
  HomeAccountTwoFactorIndexRouteImport.update({
    id: '/two-factor/',
    path: '/two-factor/',
    getParentRoute: () => HomeAccountRouteRoute,
  } as any)
const HomeAccountSecurityIndexRoute =
  HomeAccountSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => HomeAccountRouteRoute,
  } as any)
const HomeAccountEmailIndexRoute = HomeAccountEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => HomeAccountRouteRoute,
} as any)
const HomeAccountDangerZoneIndexRoute =
  HomeAccountDangerZoneIndexRouteImport.update({
    id: '/danger-zone/',
    path: '/danger-zone/',
    getParentRoute: () => HomeAccountRouteRoute,
  } as any)
const AuthTwoFactorOtpIndexRoute = AuthTwoFactorOtpIndexRouteImport.update({
  id: '/two-factor/otp/',
  path: '/two-factor/otp/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof HomeSidebarRouteRouteWithChildren
  '/home/account': typeof HomeAccountRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/a': typeof HomeSidebarARoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/auth/two-factor': typeof AuthTwoFactorIndexRoute
  '/home/account/': typeof HomeAccountIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/auth/two-factor/otp': typeof AuthTwoFactorOtpIndexRoute
  '/home/account/danger-zone': typeof HomeAccountDangerZoneIndexRoute
  '/home/account/email': typeof HomeAccountEmailIndexRoute
  '/home/account/security': typeof HomeAccountSecurityIndexRoute
  '/home/account/two-factor': typeof HomeAccountTwoFactorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof HomeIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/a': typeof HomeSidebarARoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/auth/two-factor': typeof AuthTwoFactorIndexRoute
  '/home/account': typeof HomeAccountIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/auth/two-factor/otp': typeof AuthTwoFactorOtpIndexRoute
  '/home/account/danger-zone': typeof HomeAccountDangerZoneIndexRoute
  '/home/account/email': typeof HomeAccountEmailIndexRoute
  '/home/account/security': typeof HomeAccountSecurityIndexRoute
  '/home/account/two-factor': typeof HomeAccountTwoFactorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/home/_sidebar': typeof HomeSidebarRouteRouteWithChildren
  '/home/account': typeof HomeAccountRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/_sidebar/a': typeof HomeSidebarARoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/auth/two-factor/': typeof AuthTwoFactorIndexRoute
  '/home/account/': typeof HomeAccountIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/auth/two-factor/otp/': typeof AuthTwoFactorOtpIndexRoute
  '/home/account/danger-zone/': typeof HomeAccountDangerZoneIndexRoute
  '/home/account/email/': typeof HomeAccountEmailIndexRoute
  '/home/account/security/': typeof HomeAccountSecurityIndexRoute
  '/home/account/two-factor/': typeof HomeAccountTwoFactorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/home'
    | '/home/account'
    | '/admin/'
    | '/home/'
    | '/api/auth/$'
    | '/home/a'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/home/account/'
    | '/admin/users/$userId'
    | '/auth/two-factor/otp'
    | '/home/account/danger-zone'
    | '/home/account/email'
    | '/home/account/security'
    | '/home/account/two-factor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/admin'
    | '/api/auth/$'
    | '/home/a'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/home/account'
    | '/admin/users/$userId'
    | '/auth/two-factor/otp'
    | '/home/account/danger-zone'
    | '/home/account/email'
    | '/home/account/security'
    | '/home/account/two-factor'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/home'
    | '/home/_sidebar'
    | '/home/account'
    | '/admin/'
    | '/home/'
    | '/api/auth/$'
    | '/home/_sidebar/a'
    | '/admin/users/'
    | '/auth/forgot-password/'
    | '/auth/reset-password/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/auth/two-factor/'
    | '/home/account/'
    | '/admin/users/$userId/'
    | '/auth/two-factor/otp/'
    | '/home/account/danger-zone/'
    | '/home/account/email/'
    | '/home/account/security/'
    | '/home/account/two-factor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/home/account': {
      id: '/home/account'
      path: '/account'
      fullPath: '/home/account'
      preLoaderRoute: typeof HomeAccountRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/_sidebar': {
      id: '/home/_sidebar'
      path: ''
      fullPath: '/home'
      preLoaderRoute: typeof HomeSidebarRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/account/': {
      id: '/home/account/'
      path: '/'
      fullPath: '/home/account/'
      preLoaderRoute: typeof HomeAccountIndexRouteImport
      parentRoute: typeof HomeAccountRouteRoute
    }
    '/auth/two-factor/': {
      id: '/auth/two-factor/'
      path: '/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/home/_sidebar/a': {
      id: '/home/_sidebar/a'
      path: '/a'
      fullPath: '/home/a'
      preLoaderRoute: typeof HomeSidebarARouteImport
      parentRoute: typeof HomeSidebarRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/account/two-factor/': {
      id: '/home/account/two-factor/'
      path: '/two-factor'
      fullPath: '/home/account/two-factor'
      preLoaderRoute: typeof HomeAccountTwoFactorIndexRouteImport
      parentRoute: typeof HomeAccountRouteRoute
    }
    '/home/account/security/': {
      id: '/home/account/security/'
      path: '/security'
      fullPath: '/home/account/security'
      preLoaderRoute: typeof HomeAccountSecurityIndexRouteImport
      parentRoute: typeof HomeAccountRouteRoute
    }
    '/home/account/email/': {
      id: '/home/account/email/'
      path: '/email'
      fullPath: '/home/account/email'
      preLoaderRoute: typeof HomeAccountEmailIndexRouteImport
      parentRoute: typeof HomeAccountRouteRoute
    }
    '/home/account/danger-zone/': {
      id: '/home/account/danger-zone/'
      path: '/danger-zone'
      fullPath: '/home/account/danger-zone'
      preLoaderRoute: typeof HomeAccountDangerZoneIndexRouteImport
      parentRoute: typeof HomeAccountRouteRoute
    }
    '/auth/two-factor/otp/': {
      id: '/auth/two-factor/otp/'
      path: '/two-factor/otp'
      fullPath: '/auth/two-factor/otp'
      preLoaderRoute: typeof AuthTwoFactorOtpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
  AuthTwoFactorIndexRoute: typeof AuthTwoFactorIndexRoute
  AuthTwoFactorOtpIndexRoute: typeof AuthTwoFactorOtpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
  AuthTwoFactorIndexRoute: AuthTwoFactorIndexRoute,
  AuthTwoFactorOtpIndexRoute: AuthTwoFactorOtpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HomeSidebarRouteRouteChildren {
  HomeSidebarARoute: typeof HomeSidebarARoute
}

const HomeSidebarRouteRouteChildren: HomeSidebarRouteRouteChildren = {
  HomeSidebarARoute: HomeSidebarARoute,
}

const HomeSidebarRouteRouteWithChildren =
  HomeSidebarRouteRoute._addFileChildren(HomeSidebarRouteRouteChildren)

interface HomeAccountRouteRouteChildren {
  HomeAccountIndexRoute: typeof HomeAccountIndexRoute
  HomeAccountDangerZoneIndexRoute: typeof HomeAccountDangerZoneIndexRoute
  HomeAccountEmailIndexRoute: typeof HomeAccountEmailIndexRoute
  HomeAccountSecurityIndexRoute: typeof HomeAccountSecurityIndexRoute
  HomeAccountTwoFactorIndexRoute: typeof HomeAccountTwoFactorIndexRoute
}

const HomeAccountRouteRouteChildren: HomeAccountRouteRouteChildren = {
  HomeAccountIndexRoute: HomeAccountIndexRoute,
  HomeAccountDangerZoneIndexRoute: HomeAccountDangerZoneIndexRoute,
  HomeAccountEmailIndexRoute: HomeAccountEmailIndexRoute,
  HomeAccountSecurityIndexRoute: HomeAccountSecurityIndexRoute,
  HomeAccountTwoFactorIndexRoute: HomeAccountTwoFactorIndexRoute,
}

const HomeAccountRouteRouteWithChildren =
  HomeAccountRouteRoute._addFileChildren(HomeAccountRouteRouteChildren)

interface HomeRouteRouteChildren {
  HomeSidebarRouteRoute: typeof HomeSidebarRouteRouteWithChildren
  HomeAccountRouteRoute: typeof HomeAccountRouteRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeSidebarRouteRoute: HomeSidebarRouteRouteWithChildren,
  HomeAccountRouteRoute: HomeAccountRouteRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
