/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home/route'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as Errors500Import } from './routes/errors/500'
import { Route as Errors404Import } from './routes/errors/404'
import { Route as Errors403Import } from './routes/errors/403'
import { Route as Errors401Import } from './routes/errors/401'
import { Route as HomeAccountRouteImport } from './routes/home/account/route'
import { Route as HomeTasksIndexImport } from './routes/home/tasks/index'
import { Route as HomeAccountIndexImport } from './routes/home/account/index'
import { Route as AuthSignUpIndexImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexImport } from './routes/auth/sign-in/index'
import { Route as AuthResetPasswordIndexImport } from './routes/auth/reset-password/index'
import { Route as AuthForgotPasswordIndexImport } from './routes/auth/forgot-password/index'
import { Route as AdminUsersIndexImport } from './routes/admin/users/index'
import { Route as HomeTasksCreateIndexImport } from './routes/home/tasks/create/index'
import { Route as HomeAccountSessionsIndexImport } from './routes/home/account/sessions/index'
import { Route as HomeAccountRolesIndexImport } from './routes/home/account/roles/index'
import { Route as HomeAccountDangerIndexImport } from './routes/home/account/danger/index'
import { Route as AdminUsersUserIdIndexImport } from './routes/admin/users/$userId/index'
import { Route as HomeTasksTaskIdUpdateIndexImport } from './routes/home/tasks/$taskId/update/index'
import { Route as HomeTasksTaskIdShowIndexImport } from './routes/home/tasks/$taskId/show/index'

// Create/Update Routes

const HomeRouteRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const Errors500Route = Errors500Import.update({
  id: '/errors/500',
  path: '/errors/500',
  getParentRoute: () => rootRoute,
} as any)

const Errors404Route = Errors404Import.update({
  id: '/errors/404',
  path: '/errors/404',
  getParentRoute: () => rootRoute,
} as any)

const Errors403Route = Errors403Import.update({
  id: '/errors/403',
  path: '/errors/403',
  getParentRoute: () => rootRoute,
} as any)

const Errors401Route = Errors401Import.update({
  id: '/errors/401',
  path: '/errors/401',
  getParentRoute: () => rootRoute,
} as any)

const HomeAccountRouteRoute = HomeAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => HomeRouteRoute,
} as any)

const HomeTasksIndexRoute = HomeTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => HomeRouteRoute,
} as any)

const HomeAccountIndexRoute = HomeAccountIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeAccountRouteRoute,
} as any)

const AuthSignUpIndexRoute = AuthSignUpIndexImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSignInIndexRoute = AuthSignInIndexImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthResetPasswordIndexRoute = AuthResetPasswordIndexImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const HomeTasksCreateIndexRoute = HomeTasksCreateIndexImport.update({
  id: '/tasks/create/',
  path: '/tasks/create/',
  getParentRoute: () => HomeRouteRoute,
} as any)

const HomeAccountSessionsIndexRoute = HomeAccountSessionsIndexImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => HomeAccountRouteRoute,
} as any)

const HomeAccountRolesIndexRoute = HomeAccountRolesIndexImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => HomeAccountRouteRoute,
} as any)

const HomeAccountDangerIndexRoute = HomeAccountDangerIndexImport.update({
  id: '/danger/',
  path: '/danger/',
  getParentRoute: () => HomeAccountRouteRoute,
} as any)

const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const HomeTasksTaskIdUpdateIndexRoute = HomeTasksTaskIdUpdateIndexImport.update(
  {
    id: '/tasks/$taskId/update/',
    path: '/tasks/$taskId/update/',
    getParentRoute: () => HomeRouteRoute,
  } as any,
)

const HomeTasksTaskIdShowIndexRoute = HomeTasksTaskIdShowIndexImport.update({
  id: '/tasks/$taskId/show/',
  path: '/tasks/$taskId/show/',
  getParentRoute: () => HomeRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRoute
    }
    '/home/account': {
      id: '/home/account'
      path: '/account'
      fullPath: '/home/account'
      preLoaderRoute: typeof HomeAccountRouteImport
      parentRoute: typeof HomeRouteImport
    }
    '/errors/401': {
      id: '/errors/401'
      path: '/errors/401'
      fullPath: '/errors/401'
      preLoaderRoute: typeof Errors401Import
      parentRoute: typeof rootRoute
    }
    '/errors/403': {
      id: '/errors/403'
      path: '/errors/403'
      fullPath: '/errors/403'
      preLoaderRoute: typeof Errors403Import
      parentRoute: typeof rootRoute
    }
    '/errors/404': {
      id: '/errors/404'
      path: '/errors/404'
      fullPath: '/errors/404'
      preLoaderRoute: typeof Errors404Import
      parentRoute: typeof rootRoute
    }
    '/errors/500': {
      id: '/errors/500'
      path: '/errors/500'
      fullPath: '/errors/500'
      preLoaderRoute: typeof Errors500Import
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof HomeRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/home/account/': {
      id: '/home/account/'
      path: '/'
      fullPath: '/home/account/'
      preLoaderRoute: typeof HomeAccountIndexImport
      parentRoute: typeof HomeAccountRouteImport
    }
    '/home/tasks/': {
      id: '/home/tasks/'
      path: '/tasks'
      fullPath: '/home/tasks'
      preLoaderRoute: typeof HomeTasksIndexImport
      parentRoute: typeof HomeRouteImport
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/home/account/danger/': {
      id: '/home/account/danger/'
      path: '/danger'
      fullPath: '/home/account/danger'
      preLoaderRoute: typeof HomeAccountDangerIndexImport
      parentRoute: typeof HomeAccountRouteImport
    }
    '/home/account/roles/': {
      id: '/home/account/roles/'
      path: '/roles'
      fullPath: '/home/account/roles'
      preLoaderRoute: typeof HomeAccountRolesIndexImport
      parentRoute: typeof HomeAccountRouteImport
    }
    '/home/account/sessions/': {
      id: '/home/account/sessions/'
      path: '/sessions'
      fullPath: '/home/account/sessions'
      preLoaderRoute: typeof HomeAccountSessionsIndexImport
      parentRoute: typeof HomeAccountRouteImport
    }
    '/home/tasks/create/': {
      id: '/home/tasks/create/'
      path: '/tasks/create'
      fullPath: '/home/tasks/create'
      preLoaderRoute: typeof HomeTasksCreateIndexImport
      parentRoute: typeof HomeRouteImport
    }
    '/home/tasks/$taskId/show/': {
      id: '/home/tasks/$taskId/show/'
      path: '/tasks/$taskId/show'
      fullPath: '/home/tasks/$taskId/show'
      preLoaderRoute: typeof HomeTasksTaskIdShowIndexImport
      parentRoute: typeof HomeRouteImport
    }
    '/home/tasks/$taskId/update/': {
      id: '/home/tasks/$taskId/update/'
      path: '/tasks/$taskId/update'
      fullPath: '/home/tasks/$taskId/update'
      preLoaderRoute: typeof HomeTasksTaskIdUpdateIndexImport
      parentRoute: typeof HomeRouteImport
    }
  }
}

// Create and export the route tree

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HomeAccountRouteRouteChildren {
  HomeAccountIndexRoute: typeof HomeAccountIndexRoute
  HomeAccountDangerIndexRoute: typeof HomeAccountDangerIndexRoute
  HomeAccountRolesIndexRoute: typeof HomeAccountRolesIndexRoute
  HomeAccountSessionsIndexRoute: typeof HomeAccountSessionsIndexRoute
}

const HomeAccountRouteRouteChildren: HomeAccountRouteRouteChildren = {
  HomeAccountIndexRoute: HomeAccountIndexRoute,
  HomeAccountDangerIndexRoute: HomeAccountDangerIndexRoute,
  HomeAccountRolesIndexRoute: HomeAccountRolesIndexRoute,
  HomeAccountSessionsIndexRoute: HomeAccountSessionsIndexRoute,
}

const HomeAccountRouteRouteWithChildren =
  HomeAccountRouteRoute._addFileChildren(HomeAccountRouteRouteChildren)

interface HomeRouteRouteChildren {
  HomeAccountRouteRoute: typeof HomeAccountRouteRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
  HomeTasksIndexRoute: typeof HomeTasksIndexRoute
  HomeTasksCreateIndexRoute: typeof HomeTasksCreateIndexRoute
  HomeTasksTaskIdShowIndexRoute: typeof HomeTasksTaskIdShowIndexRoute
  HomeTasksTaskIdUpdateIndexRoute: typeof HomeTasksTaskIdUpdateIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeAccountRouteRoute: HomeAccountRouteRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
  HomeTasksIndexRoute: HomeTasksIndexRoute,
  HomeTasksCreateIndexRoute: HomeTasksCreateIndexRoute,
  HomeTasksTaskIdShowIndexRoute: HomeTasksTaskIdShowIndexRoute,
  HomeTasksTaskIdUpdateIndexRoute: HomeTasksTaskIdUpdateIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/home/account': typeof HomeAccountRouteRouteWithChildren
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/home/account/': typeof HomeAccountIndexRoute
  '/home/tasks': typeof HomeTasksIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/home/account/danger': typeof HomeAccountDangerIndexRoute
  '/home/account/roles': typeof HomeAccountRolesIndexRoute
  '/home/account/sessions': typeof HomeAccountSessionsIndexRoute
  '/home/tasks/create': typeof HomeTasksCreateIndexRoute
  '/home/tasks/$taskId/show': typeof HomeTasksTaskIdShowIndexRoute
  '/home/tasks/$taskId/update': typeof HomeTasksTaskIdUpdateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/admin': typeof AdminIndexRoute
  '/home': typeof HomeIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/home/account': typeof HomeAccountIndexRoute
  '/home/tasks': typeof HomeTasksIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/home/account/danger': typeof HomeAccountDangerIndexRoute
  '/home/account/roles': typeof HomeAccountRolesIndexRoute
  '/home/account/sessions': typeof HomeAccountSessionsIndexRoute
  '/home/tasks/create': typeof HomeTasksCreateIndexRoute
  '/home/tasks/$taskId/show': typeof HomeTasksTaskIdShowIndexRoute
  '/home/tasks/$taskId/update': typeof HomeTasksTaskIdUpdateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/home/account': typeof HomeAccountRouteRouteWithChildren
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/home/account/': typeof HomeAccountIndexRoute
  '/home/tasks/': typeof HomeTasksIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/home/account/danger/': typeof HomeAccountDangerIndexRoute
  '/home/account/roles/': typeof HomeAccountRolesIndexRoute
  '/home/account/sessions/': typeof HomeAccountSessionsIndexRoute
  '/home/tasks/create/': typeof HomeTasksCreateIndexRoute
  '/home/tasks/$taskId/show/': typeof HomeTasksTaskIdShowIndexRoute
  '/home/tasks/$taskId/update/': typeof HomeTasksTaskIdUpdateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/home'
    | '/home/account'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/admin/'
    | '/home/'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/home/account/'
    | '/home/tasks'
    | '/admin/users/$userId'
    | '/home/account/danger'
    | '/home/account/roles'
    | '/home/account/sessions'
    | '/home/tasks/create'
    | '/home/tasks/$taskId/show'
    | '/home/tasks/$taskId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/admin'
    | '/home'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/home/account'
    | '/home/tasks'
    | '/admin/users/$userId'
    | '/home/account/danger'
    | '/home/account/roles'
    | '/home/account/sessions'
    | '/home/tasks/create'
    | '/home/tasks/$taskId/show'
    | '/home/tasks/$taskId/update'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/home'
    | '/home/account'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/admin/'
    | '/home/'
    | '/admin/users/'
    | '/auth/forgot-password/'
    | '/auth/reset-password/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/home/account/'
    | '/home/tasks/'
    | '/admin/users/$userId/'
    | '/home/account/danger/'
    | '/home/account/roles/'
    | '/home/account/sessions/'
    | '/home/tasks/create/'
    | '/home/tasks/$taskId/show/'
    | '/home/tasks/$taskId/update/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  Errors401Route: typeof Errors401Route
  Errors403Route: typeof Errors403Route
  Errors404Route: typeof Errors404Route
  Errors500Route: typeof Errors500Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  Errors401Route: Errors401Route,
  Errors403Route: Errors403Route,
  Errors404Route: Errors404Route,
  Errors500Route: Errors500Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/auth",
        "/home",
        "/errors/401",
        "/errors/403",
        "/errors/404",
        "/errors/500"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/",
        "/admin/users/",
        "/admin/users/$userId/"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/forgot-password/",
        "/auth/reset-password/",
        "/auth/sign-in/",
        "/auth/sign-up/"
      ]
    },
    "/home": {
      "filePath": "home/route.tsx",
      "children": [
        "/home/account",
        "/home/",
        "/home/tasks/",
        "/home/tasks/create/",
        "/home/tasks/$taskId/show/",
        "/home/tasks/$taskId/update/"
      ]
    },
    "/home/account": {
      "filePath": "home/account/route.tsx",
      "parent": "/home",
      "children": [
        "/home/account/",
        "/home/account/danger/",
        "/home/account/roles/",
        "/home/account/sessions/"
      ]
    },
    "/errors/401": {
      "filePath": "errors/401.tsx"
    },
    "/errors/403": {
      "filePath": "errors/403.tsx"
    },
    "/errors/404": {
      "filePath": "errors/404.tsx"
    },
    "/errors/500": {
      "filePath": "errors/500.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/home/": {
      "filePath": "home/index.tsx",
      "parent": "/home"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx",
      "parent": "/admin"
    },
    "/auth/forgot-password/": {
      "filePath": "auth/forgot-password/index.tsx",
      "parent": "/auth"
    },
    "/auth/reset-password/": {
      "filePath": "auth/reset-password/index.tsx",
      "parent": "/auth"
    },
    "/auth/sign-in/": {
      "filePath": "auth/sign-in/index.tsx",
      "parent": "/auth"
    },
    "/auth/sign-up/": {
      "filePath": "auth/sign-up/index.tsx",
      "parent": "/auth"
    },
    "/home/account/": {
      "filePath": "home/account/index.tsx",
      "parent": "/home/account"
    },
    "/home/tasks/": {
      "filePath": "home/tasks/index.tsx",
      "parent": "/home"
    },
    "/admin/users/$userId/": {
      "filePath": "admin/users/$userId/index.tsx",
      "parent": "/admin"
    },
    "/home/account/danger/": {
      "filePath": "home/account/danger/index.tsx",
      "parent": "/home/account"
    },
    "/home/account/roles/": {
      "filePath": "home/account/roles/index.tsx",
      "parent": "/home/account"
    },
    "/home/account/sessions/": {
      "filePath": "home/account/sessions/index.tsx",
      "parent": "/home/account"
    },
    "/home/tasks/create/": {
      "filePath": "home/tasks/create/index.tsx",
      "parent": "/home"
    },
    "/home/tasks/$taskId/show/": {
      "filePath": "home/tasks/$taskId/show/index.tsx",
      "parent": "/home"
    },
    "/home/tasks/$taskId/update/": {
      "filePath": "home/tasks/$taskId/update/index.tsx",
      "parent": "/home"
    }
  }
}
ROUTE_MANIFEST_END */
